name: Telegram Pull Request Updates
on:
  pull_request:
    types: [open]

jobs:
  pr_update:
    name: pull request update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: ${{github.repository}} - ${{github.actor}} just opened a new pull request from ${{ github.head_ref }} to ${{ github.base.ref}}.
