name: Telegram Push Updates
on: [push]

jobs:
  push_update:
    name: push_update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

      - name: send push update
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: ${{github.repository}} - ${{github.actor}} just pushed to branch ${{ steps.vars.outputs.branch }}.
